export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: '60s',

  REFRESH_TOKEN_EXPIRES_IN: '7d',

  DEFAULT_REFRESH_TOKEN_EXPIRATION_MS: 7 * 24 * 60 * 60 * 1000,

  TOKEN_CLEANUP_INTERVAL_MS: 60 * 60 * 1000,
} as const;
